---
permalink: reference-requirements-and-considerations.html 
sidebar: sidebar 
keywords: requirements, considerations 
summary: VM에 대해 BlueXP 백업 및 복구를 사용하기 전에 몇 가지 요구 사항과 고려 사항을 숙지해야 합니다. 
---
= 요구 사항 및 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VM에 대해 BlueXP 백업 및 복구를 사용하기 전에 몇 가지 요구 사항 및 고려 사항을 숙지해야 합니다.

* Windows 시스템 또는 Linux 시스템의 데이터를 보호하기 위해 플러그인을 사용하는지에 관계없이 VM용 BlueXP 백업 및 복구는 Linux VM으로 배포됩니다.
* AWS의 VMC에 VM용 BlueXP 백업 및 복구를 구축해야 합니다.
+
VM 및 VMC에 대한 BlueXP 백업 및 복구는 동일한 시간대를 사용해야 합니다. 백업 스케줄은 VM에 대한 BlueXP 백업 및 복구가 배포되는 시간대에서 실행됩니다. VMC는 VMC가 위치한 표준 시간대의 데이터를 보고합니다. 따라서 VM 및 VMC에 대한 BlueXP 백업 및 복구가 서로 다른 시간대에 있는 경우 BlueXP VM 백업 및 복구 대시보드의 데이터는 보고서의 데이터와 다를 수 있습니다.

* 특수 문자가 있는 폴더에 VM용 BlueXP 백업 및 복구를 배포해서는 안 됩니다.
+
폴더 이름에는 $!@#%^&()_+{}';., *?"<>| 같은 특수 문자가 포함될 수 없습니다

* AWS의 각 VMC에 대해 VM에 대해 별도의 고유한 BlueXP 백업 및 복구 인스턴스를 구축하고 등록해야 합니다.
+
** AWS의 각 VMC는 VM을 위한 BlueXP 백업 및 복구의 개별 인스턴스와 페어링되어야 합니다.
** VM에 대한 BlueXP 백업 및 복구의 각 인스턴스는 별도의 Linux VM으로 배포되어야 합니다.
+
예를 들어 AWS에서 6개의 서로 다른 VMC 인스턴스에서 백업을 수행하려면 6개의 호스트에 6개의 VM 인스턴스에 대해 6개의 BlueXP 백업 및 복구를 구축해야 하며, AWS의 각 VMC는 VM에 대한 BlueXP 백업 및 복구의 고유한 인스턴스와 페어링되어야 합니다.



* vmc.vmware.com 콘솔에서 방화벽 포트를 열어 컴퓨팅 게이트웨이 공용 IP가 관리 네트워크의 vCenter와 TCP 443을 통해 통신할 수 있도록 합니다.
* AWS 콘솔에서 FSx for ONTAP가 실행되는 VPC의 보안 그룹을 업데이트하여 FSx for ONTAP에 액세스하는 VM에 대한 BlueXP 백업 및 복구를 허용해야 합니다.

