---
permalink: task-restore-virtual-machines-from-amazon-fsx.html 
sidebar: sidebar 
keywords: restore, virtual machines, amazon fsx 
summary: 가상 컴퓨터를 복원할 때 선택한 백업 복사본으로 기존 콘텐츠를 덮어쓰거나 가상 시스템의 복사본을 만들 수 있습니다. 
---
= Amazon FSx에서 가상 머신을 복구합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 컴퓨터를 복원할 때 선택한 백업 복사본으로 기존 콘텐츠를 덮어쓰거나 가상 시스템의 복사본을 만들 수 있습니다.

다음 위치로 VM을 복원할 수 있습니다.

* 원래 위치로 복원합니다
+
** 원래 ESXi 호스트에 마운트된 원래 데이터 저장소에 마운트(원래 VM을 덮어씀)


* 대체 위치로 복원합니다
+
** 원래 ESXi 호스트에 마운트된 다른 데이터 저장소로
** 동일한 vCenter에서 관리되는 다른 ESXi 호스트에 마운트된 원래 데이터 저장소에 대한 데이터 저장소입니다
** 동일한 vCenter에서 관리되는 다른 ESXi 호스트에 마운트된 다른 데이터 저장소에 대한 데이터 저장소입니다
** 연결된 모드에서 다른 vCenter에서 관리하는 다른 ESXi 호스트에 마운트된 다른 데이터 저장소에 대한 데이터 저장소입니다




.시작하기 전에
* 백업이 있어야 합니다.
+
가상 머신을 복구하려면 먼저 VM에 대한 BlueXP 백업 및 복구를 사용하여 가상 머신의 백업을 생성해야 합니다.

+
[NOTE]
====
VM에 대한 BlueXP 백업 및 복구 이외의 소프트웨어에 의해 수행된 가상 컴퓨터의 스냅샷 복사본이 있는 경우 복원 작업을 성공적으로 완료할 수 없습니다.

====
* 가상 머신이 전송 중이 아니어야 합니다.
+
복구할 가상 머신이 vMotion 또는 Storage vMotion 상태가 아니어야 합니다.

* HA 구성 오류.
+
백업을 다른 위치로 복구하기 전에 vCenter ESXi 호스트 요약 화면에 표시되는 HA 구성 오류가 없는지 확인합니다.



.이 작업에 대해
* 가상 시스템이 등록 취소되어 다시 등록되었습니다.
+
가상 머신의 복구 작업은 원래 가상 머신의 등록을 해제하고, 백업 스냅샷 복사본에서 가상 머신을 복원하고, 복원된 가상 머신을 동일한 ESXi 서버에 동일한 이름과 구성으로 등록합니다. 복구 후에 가상 시스템을 리소스 그룹에 수동으로 추가해야 합니다.

* 데이터 저장소 복원 중
+
데이터 저장소를 복구할 수는 없지만 데이터 저장소의 가상 머신을 복구할 수는 있습니다.

* 가상 시스템에 대한 VMware 정합성 보장 스냅샷 장애가 발생했습니다.
+
가상 머신에 대한 VMware 정합성 보장 스냅샷이 실패하더라도 가상 머신이 백업됩니다. 복구 마법사에서 백업 복사본에 포함된 엔터티를 보고 복구 작업에 사용할 수 있습니다.



.단계
. VMware vSphere Client 도구 모음에서 * 호스트 및 클러스터 * 를 클릭한 다음 스토리지 시스템을 선택합니다.
. 왼쪽 탐색 창에서 * 가상 머신 * 을 마우스 오른쪽 버튼으로 클릭하고 드롭다운 목록에서 * VM용 BlueXP 백업 및 복구 * 를 선택한 다음 * 복원 * 을 선택하여 마법사를 시작합니다.
. 복원 * 마법사의 * 백업 선택 * 페이지에서 복원할 백업 스냅샷 복사본을 선택합니다.
+
특정 백업 이름 또는 부분 백업 이름을 검색하거나 필터 아이콘을 클릭하고 날짜 및 시간 범위를 선택하고 VMware 스냅샷을 포함하는 백업 여부, 마운트된 백업 여부 및 위치를 선택하여 백업 목록을 필터링할 수 있습니다. 확인 * 을 클릭하여 마법사로 돌아갑니다.

. 범위 선택 * 페이지의 * 복구 범위 * 필드에서 * 전체 가상 머신 * 을 선택한 다음 복구 위치를 선택한 다음 백업을 마운트할 대상 정보를 입력합니다.
+
VM 이름 필드에서 동일한 VM 이름이 있으면 새 VM 이름 형식은 '<vm_name>_<timestamp>'입니다.

+
부분 백업을 복원할 때 복원 작업은 * 범위 선택 * 페이지를 건너뜁니다.

. 복원 작업 후 가상 컴퓨터의 전원을 켜도록 하려면 * VM 다시 시작 * 확인란을 활성화합니다.
. Select Location * 페이지에서 복구된 데이터 저장소의 위치를 선택합니다.
. 요약 * 페이지를 검토한 다음 * 마침 * 을 클릭합니다.
. * 선택 사항 *: 화면 하단의 * 최근 작업 * 을 클릭하여 작업 진행 상황을 모니터링합니다.


.작업을 마친 후
* 복구된 가상 머신을 리소스 그룹에 추가합니다.
+
새로 복원된 VM이 보호되는지 확인합니다. 그렇지 않은 경우 복원된 VM을 적절한 리소스 그룹에 수동으로 추가하여 보호합니다.


