---
permalink: task-deploy-bluexp-backup-and-recovery-for-vms.html 
sidebar: sidebar 
keywords: deploy, bluexp, backup, recovery for VMs 
summary: 가상화 시스템에서 VM, 데이터 저장소 및 애플리케이션 정합성이 보장되는 데이터베이스를 보호하려면 VM을 위한 BlueXP 백업 및 복구를 구축해야 합니다. 
---
= VM용 BlueXP 백업 및 복구 배포
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 시스템에서 VM 및 데이터 저장소를 보호하려면 VM용 BlueXP 백업 및 복구를 구축해야 합니다.

.시작하기 전에
++++

[NOTE]
====
OVA 구축은 VMware vCenter 8.0 이상에서 지원됩니다.

====
* 구축 요구 사항을 읽어야 합니다.
* AWS에서 지원되는 버전의 VMC를 실행 중이어야 합니다.
* AWS 환경에서 VMC를 구성하고 설정해야 합니다.
* VM에 대한 BlueXP 백업 및 복구를 위해 ESXi 호스트를 설정해야 합니다.
* VM에 대한 BlueXP 백업 및 복구를 다운로드해야 합니다 `.tar` 파일.
* AWS 인스턴스의 VMC에 대한 로그인 인증 세부 정보가 있어야 합니다.
* 유효한 공개 및 개인 키 파일이 있는 인증서가 있어야 합니다. 자세한 내용은 스토리지 인증서 관리 섹션의 문서를 참조하십시오.
* VM에 대한 BlueXP 백업 및 복구 배포 중에 브라우저 캐시 문제를 방지하려면 vSphere Client의 모든 브라우저 세션에서 로그아웃하고 닫은 후 브라우저 캐시를 삭제해야 합니다.
* vCenter에서 TLS(Transport Layer Security)를 활성화해야 합니다. VMware 설명서를 참조하십시오.
* vCenter와 동일한 시간대에 VM에 대한 BlueXP 백업 및 복구를 구축해야 합니다.


.단계
. VMware vCenter 7.0.3 이상 버전의 경우 OVA(Open Virtual Appliance) 다운로드 섹션의 단계에 따라 인증서를 vCenter로 가져옵니다.
. 브라우저에서 VMware vSphere vCenter로 이동합니다.
. VMware vCenter Single Sign-On 페이지 * 에 로그인합니다.
. 탐색 창에서 데이터 센터, 클러스터 또는 호스트와 같은 가상 머신의 유효한 상위 객체인 인벤토리 객체를 마우스 오른쪽 버튼으로 클릭하고 * Deploy OVF Template * 을 선택하여 VMware 배포 마법사를 시작합니다.
. 의 압축을 풉니다 `.tar` 파일이 있습니다 `.ova` 파일을 로컬 시스템에 저장합니다. OVF 템플릿 선택 * 페이지에서 의 위치를 지정합니다 `.ova` 파일 내부 `.tar` 압축을 푼 폴더.
. 다음 * 을 클릭합니다.
. 이름 및 폴더 선택 * 페이지에서 VM 또는 vApp의 고유한 이름을 입력하고 구축 위치를 선택한 후 * 다음 * 을 클릭합니다.
+
이 단계는 를 가져올 위치를 지정합니다 `.ova` 파일을 vCenter에 저장합니다. VM의 기본 이름은 선택한 의 이름과 같습니다 `.ova` 파일. 기본 이름을 변경하는 경우 AWS VM 폴더의 각 VMC 내에서 고유한 이름을 선택합니다.

+
VM의 기본 배포 위치는 마법사를 시작한 인벤토리 객체입니다.

. 리소스 선택 * 페이지에서 배포된 VM 템플릿을 실행할 리소스를 선택하고 * 다음 * 을 클릭합니다.
. Review details * 페이지에서 를 확인합니다 `.ova` 템플릿 세부 정보를 입력하고 * 다음 * 을 클릭합니다.
. License Agreement * 페이지에서 * I accept all license Agreement * 확인란을 선택합니다.
. Select storage * 페이지에서 배포된 OVF 템플릿에 대한 파일의 저장 위치 및 방법을 정의합니다.
+
.. VMDK의 디스크 형식을 선택합니다.
.. VM 스토리지 정책을 선택합니다.
+
이 옵션은 대상 리소스에 스토리지 정책이 설정된 경우에만 사용할 수 있습니다.

.. 구축된 OVA 템플릿을 저장할 데이터 저장소를 선택합니다.
+
구성 파일 및 가상 디스크 파일은 데이터 저장소에 저장됩니다.

+
가상 머신 또는 vApp과 연결된 모든 가상 디스크 파일을 수용할 수 있을 만큼 큰 데이터 저장소를 선택합니다.



. 네트워크 선택 * 페이지에서 다음을 수행합니다.
+
.. 소스 네트워크를 선택하고 대상 네트워크에 매핑합니다.
+
소스 네트워크 열에는 OVA 템플릿에 정의된 모든 네트워크가 나열됩니다.

.. IP 할당 설정 * 섹션에서 필요한 IP 프로토콜을 선택한 후 * 다음 * 을 클릭합니다.
+
VM용 BlueXP 백업 및 복구는 하나의 네트워크 인터페이스를 지원합니다. 여러 네트워크 어댑터가 필요한 경우 수동으로 설정해야 합니다.



. 템플릿 사용자 정의 * 페이지에서 다음을 수행합니다.
+
.. 기존 vCenter * 에 등록 섹션에서 vCenter 이름과 가상 어플라이언스의 vCenter 자격 증명을 입력합니다.
+
vCenter 사용자 이름 * 필드에 domain\username 형식으로 사용자 이름을 입력합니다.

.. Create BlueXP backup and recovery for VMs credentials * 섹션에서 로컬 자격 증명을 입력합니다.
+
사용자 이름 * 필드에 로컬 사용자 이름을 입력합니다. 도메인 세부 정보는 포함하지 마십시오.

+
[IMPORTANT]
====
지정한 사용자 이름과 암호를 기록해 둡니다. 나중에 VM 구성에 대한 BlueXP 백업 및 복구를 수정하려면 이러한 자격 증명을 사용해야 합니다.

====
.. 유지보수 사용자의 자격 증명을 입력합니다.
.. Setup Network Properties * 에서 호스트 이름을 입력합니다.
+
... IPv4 주소, IPv4 넷마스크, IPv4 게이트웨이, IPv4 기본 DNS, IPv4 보조 DNS, 및 IPv4 검색 도메인.
+
[IMPORTANT]
====
네트워크 구성으로 DHCP를 계속 진행하려면 이 단계를 건너뛰고 네트워크 속성 설정 섹션에서 항목을 비워 둘 수 있습니다.

====


.. Setup Date and Time * 에서 vCenter가 있는 시간대를 선택합니다.


. 완료 준비 완료 * 페이지에서 페이지를 검토하고 * 마침 * 을 클릭합니다.
+
모든 호스트는 IP 주소로 구성되어야 합니다(FQDN 호스트 이름은 지원되지 않음). 배포 작업을 수행해도 사용자 입력의 유효성을 검사하지 않습니다.

+
OVF 가져오기 및 배포 작업이 완료될 때까지 기다리는 동안 Recent Tasks 창에서 구축 진행률을 볼 수 있습니다.

+
VM에 대한 BlueXP 백업 및 복구가 성공적으로 배포되면 Linux VM으로 배포되고 vCenter에 등록되며 VMware vSphere 클라이언트가 설치됩니다.

. VM에 대한 BlueXP 백업 및 복구가 배포된 VM으로 이동한 다음 * 요약 * 탭을 클릭하고 * 전원 켜기 * 상자를 클릭하여 가상 어플라이언스를 시작합니다.
. VM에 대한 BlueXP 백업 및 복구가 켜져 있는 동안 배포된 VM에 대한 BlueXP 백업 및 복구를 마우스 오른쪽 버튼으로 클릭하고 * 게스트 OS * 를 선택한 다음 * VMware 도구 설치 * 를 클릭합니다.

